# Generated by Django 5.2.15 on 2026-06-13 04:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('current_level', models.CharField(blank=True, max_length=50)),
                ('years_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('target_country', models.CharField(default='France', max_length=100)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('target_job_types', models.JSONField(blank=True, default=list)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('french_level', models.CharField(blank=True, max_length=20)),
                ('english_level', models.CharField(blank=True, max_length=20)),
                ('relocation_preference', models.CharField(blank=True, max_length=50)),
                ('remote_preference', models.CharField(blank=True, max_length=50)),
                ('profile_completion_score', models.PositiveSmallIntegerField(default=0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=150)),
                ('normalized_name', models.CharField(db_index=True, max_length=150)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('confidence', models.PositiveSmallIntegerField(default=100)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_skills', to='profiles.candidateprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'normalized_name'), name='unique_profile_skill')],
            },
        ),
    ]
