# Generated by Django 5.2.15 on 2026-06-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
    ]
