# Generated by Django 5.2.15 on 2026-06-30 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_candidateprofile_avatar_url'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileskill',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_skills', to='skills.skill'),
        ),
    ]
