# Generated by Codex on 2026-06-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privacy", "0002_deletionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentrecord",
            name="consent_text",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
