# Generated by Django 5.2.15 on 2026-06-13 12:22

import apps.jobs.models
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('base_url', models.URLField(blank=True)),
                ('source_type', models.CharField(choices=[('api', 'API'), ('manual', 'Manual'), ('fixture', 'Fixture')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug', 'is_active', 'last_successful_sync_at'], name='jobs_jobsou_slug_4a45a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial_success', 'Partial Success'), ('failed', 'Failed')], max_length=20)),
                ('trigger_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual_admin', 'Manual (Admin)'), ('startup_fixture', 'Startup Fixture'), ('retry', 'Retry')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('search_params_json', models.JSONField(blank=True, default=dict)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('marked_stale_count', models.PositiveIntegerField(default=0)),
                ('marked_expired_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_runs', to='jobs.jobsource')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('source_job_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(default='FR', max_length=100)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('contract_type', models.CharField(blank=True, max_length=255)),
                ('remote_type', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('on_site', 'On-site'), ('unknown', 'Unknown')], max_length=20)),
                ('job_type', models.CharField(choices=[('internship', 'Internship'), ('full_time_job', 'Full-time Job'), ('apprenticeship', 'Apprenticeship'), ('contract', 'Contract'), ('unknown', 'Unknown')], max_length=20)),
                ('experience_level', models.CharField(choices=[('internship', 'Internship'), ('junior', 'Junior'), ('mid_level', 'Mid-level'), ('senior', 'Senior'), ('unknown', 'Unknown')], max_length=20)),
                ('description', models.TextField()),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('last_fetched_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('stale', 'Stale'), ('expired', 'Expired'), ('removed', 'Removed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('normalization_version', models.CharField(default='ft_v1', max_length=50)),
                ('skill_extraction_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('not_enough_text', 'Not enough text')], default='pending', max_length=20)),
                ('required_skills_json', models.JSONField(blank=True, default=apps.jobs.models.default_list)),
                ('optional_skills_json', models.JSONField(blank=True, default=apps.jobs.models.default_list)),
                ('language_requirements_json', models.JSONField(blank=True, default=apps.jobs.models.default_dict)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_jobs', to='jobs.jobsource')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedJobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('detected', 'Detected'), ('unknown', 'Unknown')], max_length=20)),
                ('source', models.CharField(choices=[('rule', 'Rule'), ('llm', 'LLM'), ('admin', 'Admin'), ('source_api', 'Source API')], max_length=20)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.normalizedjob')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_requirements', to='skills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='RawJobRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_job_id', models.CharField(max_length=255)),
                ('raw_payload_json', models.JSONField()),
                ('payload_hash', models.CharField(db_index=True, max_length=64)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('last_fetched_at', models.DateTimeField()),
                ('source_status', models.CharField(blank=True, max_length=100)),
                ('normalization_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped_unchanged', 'Skipped (Unchanged)')], default='pending', max_length=20)),
                ('normalization_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingestion_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_records', to='jobs.ingestionrun')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_records', to='jobs.jobsource')),
            ],
        ),
        migrations.AddField(
            model_name='normalizedjob',
            name='raw_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_job', to='jobs.rawjobrecord'),
        ),
        migrations.AddIndex(
            model_name='ingestionrun',
            index=models.Index(fields=['source', 'status', 'started_at', 'finished_at', 'trigger_type'], name='jobs_ingest_source__6950f6_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedjobskill',
            index=models.Index(fields=['job'], name='jobs_normal_job_id_b3f3ea_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedjobskill',
            index=models.Index(fields=['skill'], name='jobs_normal_skill_i_da7d9c_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedjobskill',
            index=models.Index(fields=['requirement_type'], name='jobs_normal_require_bf9ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedjobskill',
            index=models.Index(fields=['source'], name='jobs_normal_source_9bb9c7_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedjobskill',
            index=models.Index(fields=['confidence'], name='jobs_normal_confide_939558_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='normalizedjobskill',
            unique_together={('job', 'skill', 'requirement_type')},
        ),
        migrations.AddIndex(
            model_name='rawjobrecord',
            index=models.Index(fields=['source', 'source_job_id'], name='jobs_rawjob_source__7eb203_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjobrecord',
            index=models.Index(fields=['last_seen_at'], name='jobs_rawjob_last_se_c41e62_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjobrecord',
            index=models.Index(fields=['last_fetched_at'], name='jobs_rawjob_last_fe_37cd73_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjobrecord',
            index=models.Index(fields=['normalization_status'], name='jobs_rawjob_normali_98f39b_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjobrecord',
            index=models.Index(fields=['ingestion_run'], name='jobs_rawjob_ingesti_19817f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rawjobrecord',
            unique_together={('source', 'source_job_id')},
        ),
        migrations.AddIndex(
            model_name='normalizedjob',
            index=models.Index(fields=['source', 'source_job_id'], name='jobs_normal_source__ac3ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedjob',
            index=models.Index(fields=['status'], name='jobs_normal_status_e2a654_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedjob',
            index=models.Index(fields=['job_type'], name='jobs_normal_job_typ_83fe48_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedjob',
            index=models.Index(fields=['contract_type'], name='jobs_normal_contrac_71fc9c_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedjob',
            index=models.Index(fields=['remote_type'], name='jobs_normal_remote__06e07b_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedjob',
            index=models.Index(fields=['experience_level'], name='jobs_normal_experie_12e920_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedjob',
            index=models.Index(fields=['country', 'city', 'department', 'region'], name='jobs_normal_country_030ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedjob',
            index=models.Index(fields=['published_at', 'expires_at'], name='jobs_normal_publish_b38f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedjob',
            index=models.Index(fields=['last_seen_at', 'last_fetched_at'], name='jobs_normal_last_se_3d1e17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='normalizedjob',
            unique_together={('source', 'source_job_id')},
        ),
    ]
