# Generated by Django 5.2.15 on 2026-06-16 23:17

import apps.jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_normalizedjob_search_vector_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedjob',
            name='classification_json',
            field=models.JSONField(blank=True, default=apps.jobs.models.default_dict),
        ),
        migrations.AddField(
            model_name='normalizedjob',
            name='skill_signal_quality',
            field=models.CharField(default='unknown', max_length=32),
        ),
    ]
