# Generated by Django 5.2.15 on 2026-06-17 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_normalizedjob_classification_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobIngestionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('preset', models.CharField(default='broad_it', max_length=50)),
                ('custom_keywords', models.JSONField(blank=True, default=list)),
                ('limit_per_keyword', models.PositiveIntegerField(default=50)),
                ('max_total_per_run', models.PositiveIntegerField(default=1000)),
                ('max_pages_per_keyword', models.PositiveIntegerField(default=10)),
                ('frequency_minutes', models.PositiveIntegerField(default=240)),
                ('nightly_enabled', models.BooleanField(default=True)),
                ('nightly_max_total', models.PositiveIntegerField(default=2000)),
                ('normalize_after_fetch', models.BooleanField(default=True)),
                ('enqueue_enrichment', models.BooleanField(default=True)),
                ('enrich_every_fetched_it_job', models.BooleanField(default=True)),
                ('enrichment_limit_per_run', models.PositiveIntegerField(default=1000)),
                ('expire_after_days', models.PositiveIntegerField(default=21)),
                ('mark_missing_as_stale_after_days', models.PositiveIntegerField(default=14)),
                ('dry_run', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='JobIngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial_success', 'Partial Success'), ('failed', 'Failed')], max_length=32)),
                ('trigger', models.CharField(max_length=32)),
                ('preset', models.CharField(default='broad_it', max_length=50)),
                ('keywords_json', models.JSONField(blank=True, default=list)),
                ('limit_per_keyword', models.PositiveIntegerField(default=50)),
                ('max_total', models.PositiveIntegerField(default=1000)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('created_raw_count', models.PositiveIntegerField(default=0)),
                ('updated_raw_count', models.PositiveIntegerField(default=0)),
                ('normalized_count', models.PositiveIntegerField(default=0)),
                ('skipped_duplicate_count', models.PositiveIntegerField(default=0)),
                ('expired_count', models.PositiveIntegerField(default=0)),
                ('enrichment_queued_count', models.PositiveIntegerField(default=0)),
                ('enrichment_skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobingestionconfig')),
            ],
        ),
    ]
