# Generated by Django 5.2.15 on 2026-06-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobingestionconfig_jobingestionrun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobingestionconfig',
            old_name='enqueue_enrichment',
            new_name='enrichment_enabled',
        ),
        migrations.RenameField(
            model_name='jobingestionrun',
            old_name='skipped_duplicate_count',
            new_name='duplicates_skipped_count',
        ),
        migrations.AlterField(
            model_name='jobingestionconfig',
            name='enrichment_limit_per_run',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
