# Generated by Django 5.2.15 on 2026-06-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_enqueue_enrichment_jobingestionconfig_enrichment_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobingestionconfig',
            name='daily_enrichment_limit',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='jobingestionconfig',
            name='enrichment_limit_per_run',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
