# Generated by Django 5.2.15 on 2026-06-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobingestionconfig_daily_enrichment_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobingestionconfig',
            name='expire_grace_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='jobingestionconfig',
            name='max_jobs_per_run',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='jobingestionconfig',
            name='max_pages_per_query',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='jobingestionconfig',
            name='page_size',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='jobingestionconfig',
            name='queries_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobingestionconfig',
            name='removed_after_hours',
            field=models.PositiveIntegerField(default=72),
        ),
        migrations.AddField(
            model_name='jobingestionconfig',
            name='stale_after_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='jobingestionconfig',
            name='target_daily_fetch_count',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='jobingestionrun',
            name='query_stats_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=500)),
                ('normalized_query', models.CharField(blank=True, max_length=500)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('filters_json', models.JSONField(blank=True, default=dict)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('user_hash', models.CharField(blank=True, max_length=64)),
                ('session_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='jobs_search_created_8def8e_idx'), models.Index(fields=['query'], name='jobs_search_query_da90fc_idx'), models.Index(fields=['company'], name='jobs_search_company_063d1c_idx'), models.Index(fields=['user_hash'], name='jobs_search_user_ha_e66102_idx')],
            },
        ),
    ]
