# Generated by Django 5.2.15 on 2026-06-30 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobingestionconfig_expire_grace_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobIngestionQueryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_label', models.CharField(blank=True, max_length=120)),
                ('params_json', models.JSONField(blank=True, default=dict)),
                ('requested_range_json', models.JSONField(blank=True, default=dict)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='searchquerylog',
            name='had_invalid_filters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchquerylog',
            name='normalized_company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='searchquerylog',
            name='skill',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='searchquerylog',
            name='was_whitespace_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobingestionconfig',
            name='max_jobs_per_run',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='jobingestionconfig',
            name='page_size',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='jobingestionconfig',
            name='removed_after_hours',
            field=models.PositiveIntegerField(default=168),
        ),
        migrations.AlterField(
            model_name='jobingestionconfig',
            name='stale_after_hours',
            field=models.PositiveIntegerField(default=48),
        ),
        migrations.AddIndex(
            model_name='searchquerylog',
            index=models.Index(fields=['normalized_query'], name='jobs_search_normali_623385_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquerylog',
            index=models.Index(fields=['normalized_company'], name='jobs_search_normali_47a277_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquerylog',
            index=models.Index(fields=['result_count'], name='jobs_search_result__7a5d30_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquerylog',
            index=models.Index(fields=['had_invalid_filters'], name='jobs_search_had_inv_d28d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquerylog',
            index=models.Index(fields=['was_whitespace_only'], name='jobs_search_was_whi_32f3e1_idx'),
        ),
        migrations.AddField(
            model_name='jobingestionqueryrun',
            name='ingestion_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_runs', to='jobs.jobingestionrun'),
        ),
        migrations.AddIndex(
            model_name='jobingestionqueryrun',
            index=models.Index(fields=['ingestion_run'], name='jobs_jobing_ingesti_8224a5_idx'),
        ),
        migrations.AddIndex(
            model_name='jobingestionqueryrun',
            index=models.Index(fields=['query_label'], name='jobs_jobing_query_l_cc3a20_idx'),
        ),
        migrations.AddIndex(
            model_name='jobingestionqueryrun',
            index=models.Index(fields=['started_at'], name='jobs_jobing_started_28e336_idx'),
        ),
        migrations.AddIndex(
            model_name='jobingestionqueryrun',
            index=models.Index(fields=['error_count'], name='jobs_jobing_error_c_37ab86_idx'),
        ),
    ]
