# Generated by Django 5.2.15 on 2026-06-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_update_phase_16b_default_config_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobingestionrun',
            name='config_snapshot_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
