# Generated by Django 5.2.15 on 2026-06-30 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0010_jobingestionrun_config_snapshot_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedjob',
            name='quality_issue',
            field=models.CharField(blank=True, choices=[('not_it', 'Not IT'), ('wrong_skills', 'Wrong Skills'), ('wrong_level', 'Wrong Level'), ('expired', 'Expired'), ('duplicate', 'Duplicate'), ('source_noise', 'Source Noise')], max_length=32),
        ),
        migrations.CreateModel(
            name='JobQualityFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('not_it', 'Not IT'), ('wrong_skills', 'Wrong Skills'), ('wrong_level', 'Wrong Level'), ('expired', 'Expired'), ('duplicate', 'Duplicate'), ('source_noise', 'Source Noise')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_feedback', to='jobs.normalizedjob')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_quality_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='jobqualityfeedback',
            index=models.Index(fields=['job'], name='jobs_jobqua_job_id_2966f6_idx'),
        ),
        migrations.AddIndex(
            model_name='jobqualityfeedback',
            index=models.Index(fields=['reason'], name='jobs_jobqua_reason_54f5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='jobqualityfeedback',
            index=models.Index(fields=['created_at'], name='jobs_jobqua_created_4bc534_idx'),
        ),
        migrations.AddIndex(
            model_name='jobqualityfeedback',
            index=models.Index(fields=['reviewed_by'], name='jobs_jobqua_reviewe_79f1db_idx'),
        ),
    ]
