# Generated by Django 5.2.15 on 2026-07-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_phase_16e_quality_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobingestionconfig',
            name='frequency_minutes',
            field=models.PositiveIntegerField(default=360),
        ),
        migrations.AlterField(
            model_name='jobingestionconfig',
            name='max_jobs_per_run',
            field=models.PositiveIntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='jobingestionconfig',
            name='max_total_per_run',
            field=models.PositiveIntegerField(default=250),
        ),
    ]
