# Generated by Django 5.2.15 on 2026-06-30 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_set_default_site_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('suppressed', 'Suppressed')], default='open', max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('sent_to', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminFileAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50)),
                ('object_public_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('download', 'Download'), ('view_metadata', 'View Metadata')], max_length=50)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='adminalertevent',
            index=models.Index(fields=['alert_type', 'created_at'], name='core_admina_alert_t_a8a158_idx'),
        ),
        migrations.AddIndex(
            model_name='adminalertevent',
            index=models.Index(fields=['severity', 'status', 'created_at'], name='core_admina_severit_3d33b1_idx'),
        ),
        migrations.AddIndex(
            model_name='adminalertevent',
            index=models.Index(fields=['status', 'created_at'], name='core_admina_status_60e12a_idx'),
        ),
        migrations.AddIndex(
            model_name='adminfileaccesslog',
            index=models.Index(fields=['admin_user', 'created_at'], name='core_adminf_admin_u_caa9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='adminfileaccesslog',
            index=models.Index(fields=['object_type', 'object_public_id'], name='core_adminf_object__67d124_idx'),
        ),
        migrations.AddIndex(
            model_name='adminfileaccesslog',
            index=models.Index(fields=['action', 'created_at'], name='core_adminf_action_920147_idx'),
        ),
    ]
