# Generated by Django 5.2.15 on 2026-06-15 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cvs', '0001_initial'),
        ('jobs', '0002_normalizedjob_search_vector_gin'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('cv_uploaded', 'CV Uploaded'), ('cv_replaced', 'CV Replaced'), ('profile_updated', 'Profile Updated'), ('new_jobs_imported', 'New Jobs Imported'), ('dashboard_stale_refresh', 'Dashboard Stale Refresh'), ('nightly_refresh', 'Nightly Refresh'), ('manual_admin', 'Manual Admin')], max_length=64)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial_success', 'Partial Success'), ('failed', 'Failed')], max_length=32)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('candidate_jobs_count', models.PositiveIntegerField(default=0)),
                ('scored_jobs_count', models.PositiveIntegerField(default=0)),
                ('stored_recommendations_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_score', models.PositiveSmallIntegerField()),
                ('ranking_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rank', models.PositiveIntegerField()),
                ('strong_skills_json', models.JSONField(blank=True, default=list)),
                ('missing_skills_json', models.JSONField(blank=True, default=list)),
                ('risk_flags_json', models.JSONField(blank=True, default=list)),
                ('profile_signals_json', models.JSONField(blank=True, default=list)),
                ('reason_summary', models.TextField(blank=True)),
                ('recommendation_version', models.CharField(default='reco_v1', max_length=32)),
                ('computed_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('stale', 'Stale'), ('dismissed', 'Dismissed'), ('expired_job', 'Expired Job')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvs.cvupload')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.normalizedjob')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.candidateprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status', '-ranking_score'], name='recommendat_user_id_9be179_idx'), models.Index(fields=['user', 'rank'], name='recommendat_user_id_57027d_idx'), models.Index(fields=['job', 'status'], name='recommendat_job_id_3409f2_idx'), models.Index(fields=['computed_at'], name='recommendat_compute_80ebc5_idx'), models.Index(fields=['recommendation_version'], name='recommendat_recomme_ef7980_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'job', 'recommendation_version'), name='unique_user_job_version')],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.normalizedjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='recommendat_user_id_bb13c6_idx'), models.Index(fields=['job'], name='recommendat_job_id_42012e_idx'), models.Index(fields=['saved_at'], name='recommendat_saved_a_f2e3a9_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'job'), name='unique_saved_job')],
            },
        ),
    ]
