# Generated by Django 5.2.15 on 2026-06-30 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationQualityFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('irrelevant', 'Non pertinent'), ('too_junior', 'Trop Junior'), ('too_senior', 'Trop Senior'), ('bad_location', 'Mauvaise localisation'), ('good_recommendation', 'Bonne recommandation'), ('other', 'Autre')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_feedback', to='recommendations.jobrecommendation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_quality_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['recommendation'], name='recommendat_recomme_856190_idx'), models.Index(fields=['reason'], name='recommendat_reason_2c41ad_idx'), models.Index(fields=['created_at'], name='recommendat_created_c804df_idx'), models.Index(fields=['reviewed_by'], name='recommendat_reviewe_b8b3c3_idx')],
            },
        ),
    ]
