# Generated by Django 5.2.15 on 2026-06-14 22:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cvs', '0001_initial'),
        ('jobs', '0002_normalizedjob_search_vector_gin'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('profile_snapshot_json', models.JSONField(default=dict)),
                ('job_snapshot_json', models.JSONField(default=dict)),
                ('fit_score', models.PositiveSmallIntegerField()),
                ('technical_skills_score', models.PositiveSmallIntegerField()),
                ('experience_score', models.PositiveSmallIntegerField()),
                ('role_title_score', models.PositiveSmallIntegerField()),
                ('language_score', models.PositiveSmallIntegerField()),
                ('location_score', models.PositiveSmallIntegerField()),
                ('strong_skills_json', models.JSONField(blank=True, default=list)),
                ('missing_required_skills_json', models.JSONField(blank=True, default=list)),
                ('missing_optional_skills_json', models.JSONField(blank=True, default=list)),
                ('risk_flags_json', models.JSONField(blank=True, default=list)),
                ('profile_signals_json', models.JSONField(blank=True, default=list)),
                ('recommended_actions_json', models.JSONField(blank=True, default=list)),
                ('llm_explanation_status', models.CharField(choices=[('not_requested', 'Not Requested'), ('disabled', 'Disabled'), ('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed')], default='not_requested', max_length=50)),
                ('llm_explanation_text', models.TextField(blank=True)),
                ('scoring_version', models.CharField(default='score_v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvs.cvupload')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_results', to='jobs.normalizedjob')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.candidateprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['public_id'], name='matching_ma_public__055ea0_idx'), models.Index(fields=['user', 'job'], name='matching_ma_user_id_110d08_idx'), models.Index(fields=['user', 'created_at'], name='matching_ma_user_id_9e3cef_idx'), models.Index(fields=['job', 'fit_score'], name='matching_ma_job_id_11716a_idx'), models.Index(fields=['fit_score'], name='matching_ma_fit_sco_115bc8_idx'), models.Index(fields=['created_at'], name='matching_ma_created_4bee51_idx'), models.Index(fields=['llm_explanation_status'], name='matching_ma_llm_exp_a498e3_idx'), models.Index(fields=['scoring_version'], name='matching_ma_scoring_8b8e95_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuickMatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('session_key_hash', models.CharField(db_index=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('entered_skills_json', models.JSONField(default=list)),
                ('normalized_skills_json', models.JSONField(blank=True, default=list)),
                ('experience_level', models.CharField(max_length=50)),
                ('french_level', models.CharField(max_length=50)),
                ('estimated_fit_score', models.PositiveSmallIntegerField()),
                ('matched_skills_json', models.JSONField(blank=True, default=list)),
                ('missing_skills_json', models.JSONField(blank=True, default=list)),
                ('risk_flags_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quick_match_sessions', to='jobs.normalizedjob')),
            ],
            options={
                'indexes': [models.Index(fields=['public_id'], name='matching_qu_public__0a0589_idx'), models.Index(fields=['session_key_hash'], name='matching_qu_session_f33362_idx'), models.Index(fields=['ip_hash'], name='matching_qu_ip_hash_b0de2d_idx'), models.Index(fields=['job'], name='matching_qu_job_id_cdd002_idx'), models.Index(fields=['created_at'], name='matching_qu_created_526e97_idx'), models.Index(fields=['expires_at'], name='matching_qu_expires_9e26b7_idx'), models.Index(fields=['estimated_fit_score'], name='matching_qu_estimat_4f535b_idx')],
            },
        ),
    ]
