# Generated by Django 5.2.15 on 2026-06-30 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchQualityFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('too_junior', 'Trop Junior'), ('too_senior', 'Trop Senior'), ('missing_key_skill', 'Compétence clé manquante'), ('wrong_location', 'Mauvaise localisation'), ('language_barrier', 'Barrière linguistique'), ('not_it', 'Non IT'), ('good_match', 'Bon Match'), ('other', 'Autre')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_feedback', to='matching.matchresult')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_quality_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['match_result'], name='matching_ma_match_r_47973b_idx'), models.Index(fields=['reason'], name='matching_ma_reason_c634e2_idx'), models.Index(fields=['created_at'], name='matching_ma_created_1ca61d_idx'), models.Index(fields=['reviewed_by'], name='matching_ma_reviewe_8a117a_idx')],
            },
        ),
    ]
