# Generated by Django 5.2.15 on 2026-06-13 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('programming_language', 'Programming Language'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps'), ('cloud', 'Cloud'), ('testing', 'Testing'), ('data_ai', 'Data/AI'), ('mobile', 'Mobile'), ('tools', 'Tools'), ('methodology', 'Methodology'), ('soft_skill', 'Soft Skill'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('esco_uri', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='skills_skil_slug_2fd1f3_idx'), models.Index(fields=['canonical_name'], name='skills_skil_canonic_24a645_idx'), models.Index(fields=['category'], name='skills_skil_categor_853dbf_idx'), models.Index(fields=['is_active'], name='skills_skil_is_acti_a22cb2_idx'), models.Index(fields=['source'], name='skills_skil_source_3f194e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('normalized_alias', models.CharField(max_length=255, unique=True)),
                ('language', models.CharField(default='unknown', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='skills.skill')),
            ],
            options={
                'indexes': [models.Index(fields=['skill'], name='skills_skil_skill_i_1f2ae9_idx'), models.Index(fields=['normalized_alias'], name='skills_skil_normali_6bbd0f_idx'), models.Index(fields=['language'], name='skills_skil_languag_98953e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnmatchedSkillCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_skill_text', models.CharField(max_length=255)),
                ('normalized_text', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('cv', 'CV'), ('job', 'Job'), ('quick_match', 'Quick Match'), ('manual', 'Manual'), ('admin', 'Admin'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('source_model', models.CharField(blank=True, max_length=100, null=True)),
                ('source_object_id', models.BigIntegerField(blank=True, null=True)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('mapped', 'Mapped'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapped_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapped_candidates', to='skills.skill')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['normalized_text'], name='skills_unma_normali_946b4e_idx'), models.Index(fields=['source_type'], name='skills_unma_source__401aa9_idx'), models.Index(fields=['status'], name='skills_unma_status_fd5f37_idx'), models.Index(fields=['mapped_skill'], name='skills_unma_mapped__c3f352_idx'), models.Index(fields=['reviewed_by'], name='skills_unma_reviewe_1d10fe_idx'), models.Index(fields=['occurrence_count'], name='skills_unma_occurre_6f4d43_idx'), models.Index(fields=['created_at'], name='skills_unma_created_1bc478_idx')],
                'constraints': [models.UniqueConstraint(fields=('normalized_text', 'source_type'), name='unique_unmatched_skill')],
            },
        ),
    ]
