# Generated by Django 5.2.15 on 2026-06-17 00:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_normalizedjob_classification_json_and_more'),
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEnrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('validation_error', 'Validation error'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=32)),
                ('status_reason', models.TextField(blank=True, default='')),
                ('payload_hash', models.CharField(db_index=True, max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('raw_request_json', models.JSONField(blank=True, default=dict)),
                ('raw_response_text', models.TextField(blank=True, default='')),
                ('raw_response_json', models.JSONField(blank=True, default=dict)),
                ('validated_output_json', models.JSONField(blank=True, default=dict)),
                ('validation_errors_json', models.JSONField(blank=True, default=list)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment', to='jobs.normalizedjob')),
            ],
        ),
    ]
