# Generated by Django 5.2.15 on 2026-06-14 22:11

import apps.cvs.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(storage=apps.cvs.models.PrivateMediaStorage(), upload_to=apps.cvs.models.cv_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('parsed', 'Parsed'), ('parsed_with_warnings', 'Parsed with Warnings'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='pending', max_length=50)),
                ('parse_error', models.TextField(blank=True)),
                ('text_extraction_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('too_little_text', 'Too Little Text')], default='pending', max_length=50)),
                ('extracted_text_length', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CVParsedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True)),
                ('deterministic_json', models.JSONField(default=dict)),
                ('llm_json', models.JSONField(default=dict)),
                ('merged_json', models.JSONField(default=dict)),
                ('extraction_method', models.CharField(blank=True, choices=[('regex_only', 'Regex Only'), ('regex_llm', 'Regex + LLM'), ('manual', 'Manual'), ('failed', 'Failed')], max_length=50)),
                ('llm_schema_version', models.CharField(blank=True, max_length=50)),
                ('extracted_name', models.CharField(blank=True, max_length=255)),
                ('extracted_email', models.EmailField(blank=True, max_length=254)),
                ('extracted_phone', models.CharField(blank=True, max_length=50)),
                ('extracted_location', models.CharField(blank=True, max_length=255)),
                ('extracted_linkedin_url', models.URLField(blank=True)),
                ('extracted_github_url', models.URLField(blank=True)),
                ('extracted_portfolio_url', models.URLField(blank=True)),
                ('estimated_years_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('confidence_json', models.JSONField(default=dict)),
                ('warnings_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_data', to='cvs.cvupload')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cvupload',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('user',), name='unique_active_cv_per_user'),
        ),
    ]
