# Generated by Django 5.2.15 on 2026-06-30 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVFieldCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('extracted_value', models.TextField(blank=True)),
                ('corrected_value', models.TextField(blank=True)),
                ('confidence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('system', 'System')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_corrections', to='cvs.cvupload')),
                ('source_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['cv_upload', 'field_name'], name='cvs_cvfield_cv_uplo_dabdec_idx'), models.Index(fields=['source', 'created_at'], name='cvs_cvfield_source_3f4ee1_idx')],
            },
        ),
    ]
